# Welcome to Jekyll!

# Site settings
title: Chamini Hasanga
email: hasanga.au@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a Software Engineer living in Brisbane. This web space is
  for the things I want to share related to my technology sphere.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: chamini_hasanga
github_username:  chaminihasanga

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed
